### ISSUE TITLE
mapNewBlock used in getwork() is never pruned.

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#23] opened 2016-11-27 20:05 UTC
### Describe the issue
When running getwork, mapNewBlock is a static pointer and the underlying std::map is never cleared.  The map gets large and could potentially crash the wallet.
### Steps to reproduce
1. Run Qt Creator and add a debug stop on the first line of the getwork function in rpcmining.cpp
2. Run the wallet with Qt in debug mode.
3. Run CPUMiner and use getwork, not getblocktemplate.
4. When the debugger hits the break point, the size of mapNewBlock should be fairly large. 
### Expected behavior (tell us what should happen)
mapNewBlock should be pruned so it doesn't cause memory issues.
### Screenshots
![alt text](https://camo.githubusercontent.com/e4ac2eb3216a647e43a38306584b816b1a693917/687474703a2f2f692e696d6775722e636f6d2f5166584d6d44752e706e67 "Logo Title Text 1")
### What platform are you using (Linux, Windows, Mac)
Linux Ubuntu 16.04 64-bit.

**Comment by GregoryBetz** [comment] 2016-12-04 04:29
Wasn't getwork changed to another function and then gradually phased out for better ones? We are having a hell of a lot of problems with something that I think should be fixed on the mining software to be honest.

**Comment by SCDeveloper** [comment] 2017-02-25 19:16
I have possibly just fixed this in the v1.0.0.0 branch:

            if (pindexPrev != chainActive.Tip())
            {
                // Deallocate old blocks since they're obsolete now
                mapNewBlock.clear();
                BOOST_FOREACH(CBlockTemplate* pblocktemplate, vNewBlockTemplate)
                    delete pblocktemplate;
                vNewBlockTemplate.clear();
            }

**Comment by SCDeveloper** [comment] 2017-02-25 19:16
testing now

**Comment by SCDeveloper** [comment] 2017-02-25 19:42
In OSX when I find a block the memory increases from 158MB to 168MB and then back down to 158MB. Looks like it is working.

**Comment by SCDeveloper** [comment] 2017-02-25 21:09
Nope its just my OSX being better than Windows. I added this code to GetWork() when the issue is with GetBlockTemplate(). Bitcoin also has this issue.

**Comment by SCDeveloper** [comment] 2017-03-06 10:47
Build issue on Gitian/MinGW possibly and GCC.

**Comment by SCDeveloper** [comment] 2017-03-15 21:07
Use of deprecated code, auto_ptr. Amended in v1.1.0.0

**Closed by SCDeveloper** 2017-03-15 21:07 UTC
Labels: bug
